language: node_js
matrix:
  include:
    - node_js: "0.10"
      env: GULP_TASK="Nodeunit"
    - node_js: "0.11"
      env: GULP_TASK="Nodeunit"
    - node_js: "iojs"
      env: GULP_TASK="Nodeunit"
    - node_js: "0.10"
      env: GULP_TASK="Qunit-Farm"
  fast_finish: true

notifications:
  email: false

